# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: demo-ig
#   namespace: {{ .Values.namespace }}
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /api(/|$)(.*)
#           pathType: Prefix
#           backend:
#             service:
#               name: demo-chart
#               port:
#                 number: 8085
            